# Aufruf:   docker compose up

services:
  trivy:
    image: aquasec/trivy:0.49.1
    command: [image, juergenzimmermann/packstation:2024.04.0-bookworm]
    volumes:
      - type: bind
        source: ~/volumes/trivy
        target: /root/.cache
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    container_name: trivy
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '2.0'
          memory: 2G
