global:
  # How frequently to scrape ("kratzen") target
  scrape_interval: 3s

# https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config
scrape_configs:
  - job_name: buch
    scheme: https
    # https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tls_config
    tls_config:
      ca_file: /etc/prometheus/certificate.crt
      insecure_skip_verify: true
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          application: buch
