' Preview durch <Alt>d

@startuml ER Diagramm

' hide the spot
hide circle

' evtl. Prbleme mit Kraehenfuessen vermeiden
skinparam linetype ortho

entity "Packstation" {
  * id: integer <<generated>>
  --
  * version: integer
  * nummer: text
    baudatum: integer
  * **typ_id**: integer <<FK>>
  * stadt: text
  * erzeugt: timestamp
  * aktualisiert: timestamp
}

entity "Typ" {
  * id: integer <<generated>>
  --
  * name: text
    beschreibung: text
}

entity "Paket" {
  * id: integer <<generated>>
  --
    **packstation_id**: integer <<FK>>
  * packnummer: text
    gewicht: number
}

Packstation ||..|| Typ
Packstation ||..o{ Paket

@enduml
