' Preview durch <Alt>d

@startuml Komponenten

left to right direction

actor RESTClient
actor GraphQLClient

node "Nest" {
  [RequestLoggerMiddleware]

  [PackstationController]
  [PackstationResolver]

  [PackstationService]

  [Repository<Packstation>]

  [MailService]
}


cloud {
    [TypeORM]
}

cloud {
    [nest-keycloak-connect]
}

cloud {
    [nodemailer]
}

database "DB packstation" {
    [Tabelle packstation]
    [Tabelle adresse]
    [Tabelle paket]
}

node {
    [Keycloak]
}

node {
    [Mailserver]
}

RESTClient ~~> [RequestLoggerMiddleware]
GraphQLClient ~~> [RequestLoggerMiddleware]

[RequestLoggerMiddleware] ~~> [PackstationController]
[RequestLoggerMiddleware] ~~> [PackstationResolver]

[PackstationController] ..> [PackstationService]
[PackstationResolver] ..> [PackstationService]
[PackstationService] ..> [Repository<Packstation>]

[Repository<Packstation>] ~~> [TypeORM]
[TypeORM] ~~> [Tabelle packstation]
[TypeORM] ~~> [Tabelle adresse]
[TypeORM] ~~> [Tabelle paket]

[PackstationController] ..> [nest-keycloak-connect]
[nest-keycloak-connect] ~~> [Keycloak]

[PackstationService] ..> [MailService]
[MailService] ~~> [nodemailer]
[nodemailer] ~~> [Mailserver]

[MailService] ~[hidden]~> [nest-keycloak-connect]

@enduml
