' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml Komponenten

left to right direction

actor RESTClient
actor GraphQLClient

node "Nest" {
  [RequestLoggerMiddleware]

  [PackstationController]
  [PackstationResolver]

  [PackstationService]

  [Repository<Packstation>]

  [MailService]
}


cloud {
    [TypeORM]
}

cloud {
    [nest-keycloak-connect]
}

cloud {
    [nodemailer]
}

database "DB packstation" {
    [Tabelle packstation]
    [Tabelle titel]
    [Tabelle abbildung]
}

node {
    [Keycloak]
}

node {
    [Mailserver]
}

RESTClient ~~> [RequestLoggerMiddleware]
GraphQLClient ~~> [RequestLoggerMiddleware]

[RequestLoggerMiddleware] ~~> [PackstationController]
[RequestLoggerMiddleware] ~~> [PackstationResolver]

[PackstationController] ..> [PackstationService]
[PackstationResolver] ..> [PackstationService]
[PackstationService] ..> [Repository<Packstation>]

[Repository<Packstation>] ~~> [TypeORM]
[TypeORM] ~~> [Tabelle packstation]
[TypeORM] ~~> [Tabelle titel]
[TypeORM] ~~> [Tabelle abbildung]

[PackstationController] ..> [nest-keycloak-connect]
[nest-keycloak-connect] ~~> [Keycloak]

[PackstationService] ..> [MailService]
[MailService] ~~> [nodemailer]
[nodemailer] ~~> [Mailserver]

[MailService] ~[hidden]~> [nest-keycloak-connect]

footer (c) Jürgen Zimmermann

@enduml
