# ==============================================================================
# N o d e
# ==============================================================================
#node:
#  port: 3000

# ==============================================================================
# D a t e n b a n k
# ==============================================================================

# "pg-native" erfordert die Installation von PostgreSQL: Docker-Image genügt nicht
# "better-sqlite3" erfordert Python zum Uebersetzen, wenn das Docker-Image gebaut wird

db:
  #type: postgres
  #type: sqlite

  host: postgres

  #username: packstation
  #password: p
  #passwordAdmin: p
  #name: packstation
  populate: true

# ==============================================================================
# K e y c l o a k
# ==============================================================================
keycloak:
  authServerUrl: http://keycloak:8080
  #realm: acme
  # siehe Keycloak Menuepunkt "Clients" > Tab "Clients list" > Spalte "Client ID"
  #clientId: packstation-client
  #tokenValidation: online

# ==============================================================================
# L o g g i n g
# ==============================================================================
log:
  level: debug
  dir: /tmp
  pretty: true
  #default: true

# ==============================================================================
# H e a l t h
# ==============================================================================
health:
  prettyPrint: true

# ==============================================================================
# J W T
# ==============================================================================
# 1d = 1 Tag, 1h = 1 Stunde, 1m = 1 Minute, 1s = 1 Sekunde
#jwt:
#  expiresIn: 1h
#  issuer: https://hka.de/JuergenZimmermann

# ==============================================================================
# M a i l s e r v e r
# ==============================================================================
mail:
  #activated: false
  host: fakesmtp
  port: 8025
  log: false

# ==============================================================================
# Authentifizierung
# ==============================================================================
auth:
  # https://github.com/docker/compose/issues/6741: '' wegen $
  passwordEncoded: '$argon2i$v=19$m=4096,t=3,p=1$aaxA2v/9rRSPGkwYN+NQog$27Huii1XtD3iEd62fog+04G26LRPZMHoYCI6AGKTL8M'
